name: CI - Build and Push Wisecow Image

on:
  push:
    branches: [ "main" ]   # Trigger workflow when code is pushed to the main branch
  pull_request:
    branches: [ "main" ]   # Also run on pull requests targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to DockerHub using GitHub Secrets
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t satyendra1999/wisecow:latest .

      # Step 4: Push the Docker image to DockerHub
      - name: Push Docker image
        run: docker push satyendra1999/wisecow:latest
